Add a checker and raise an error if there are not cut-files
JYU-IBA/potku pull request #213
Opened 2021-11-16 10:25 UTC by jkpnen

FIX: #212

2021-11-16 14:35 UTC, tpitkanen commented on widgets/detector_settings.py
> +                    f"continue?",
The wording on this warning is a bit ambiguous. Does it mean
1. "None of the measurements have a cut file for the element {eff_file.stem}.\nDo you want to continue?" or
2. "At least one of the measurements is missing a cut file for the element {eff_file.stem}\nDo You want to continue?"?

2021-11-22 18:00 UTC, tpitkanen requested changes
I tested this with **H.eff** and could not add the efficiency file if the *H* element wasn't already in a measurement.

# Steps to reproduce

1. Open a request with a measurement (e.g. gradu-2021-11-27-copy)
2. Open a measurement
3. Make sure that there are no corresponding selections/cuts for the efficiency that you are about to add
4. Request Settings... > Detector > Efficiencies > + (add efficiency)

## Expected behavior

Potku prompts for confirmation.

(Potku used to allow adding the efficiency file without asking anything.)

## Actual behavior

Nothing happens. (`__check_if_selected_elements_have_cut_files` returns `None` because `eff_files_elements` is empty. The inner `QMessageBox.warning` is not reached.)

## Fix

- always return something (in general: if one code path returns a value, all the other ones must return something too)
- rethink the `for file in eff_files_elements:` check so that the message box is reached

2021-11-23 10:01 UTC, jkpnen commented
Thanks. Silly mistake.

2021-11-23 10:46 UTC, tpitkanen approved these changes
Looks good to me. I'll push that one fix and then merge this.

(Now we could add a unit test for this, but testing the GUI is kind of complicated so let's just skip that.)

2021-11-23 10:46 UTC, tpitkanen commented on widgets/detector_settings.py
> +        if len(eff_files_elements) is 0:
Don't compare numbers by identity (`is`), use equality (`==`). Using `is` is roughly the same as doing `id(x) == id(y)`. CPython caches the first 100 or so number objects, so this works, but it's only an implementation detail. Example of bad things happening:

```python
>>> a = 100
>>> a is 100
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
True
>>> b = 1000
>>> b is 1000
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
False
>>> b == 1000
True
```

```suggestion
        if len(eff_files_elements) == 0:
```

2021-11-23 11:29 UTC, jkpnen commented
> Looks good to me. I'll push that one fix and then merge this.
> 
> (Now we could add a unit test for this, but testing the GUI is kind of complicated so let's just skip that.)

Okay, thanks.

2021-11-23 11:31 UTC, merged